name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Check HTML content before deploy (debugging step)
    - name: Check HTML content before deploy
      run: |
        cat ./index.html  # Replace with the correct path to your HTML file if needed

    # Step 3: Replace placeholder with secret values
    - name: Inject AdSense Publisher ID and Google Site Verification
      run: |
        sed -i "s/{{ADSENSE_ID}}/$ADSENSE_ID_GOOGLE/g" ./index.html
        sed -i "s/{{SITE_VERIFICATION}}/$GOOGLE_SITE_VERIFICATION/g" ./index.html
      env:
        ADSENSE_ID_GOOGLE: ${{ secrets.ADSENSE_ID_GOOGLE }}
        GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_SITE_VERIFICATION }}

    # Step 4: Check HTML content after inject (debugging step)
    - name: Check HTML content after inject
      run: |
        cat ./index.html  # Confirm the meta tags were injected

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./  # The directory to deploy from (root in this case)
      
    # Step 6: Debugging deployment directory content (check the files that are being deployed)
    - name: List files in publish directory
      run: |
        ls -la ./  # List files to confirm the correct files are being deployed
