name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject AdSense Publisher ID and Google Site Verification
      run: |
        sed -i "s/{{ADSENSE_ID}}/$ADSENSE_ID/g" index.html
        sed -i "s/{{GOOGLE_SITE_VERIFICATION}}/$GOOGLE_SITE_VERIFICATION/g" index.html
      env:
        ADSENSE_ID: ${{ secrets.ADSENSE_ID }}
        GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_SITE_VERIFICATION }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./  # Update this to your build directory if needed
